name: Daily IG Scrape

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

     - name: Install dependencies
  run: pip install requests beautifulsoup4


      - name: Run scraper
        run: python scrape_instagram.py
